config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :links
      resources :users
      resources :views

      root to: "links#index"
    end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  resources :links
  resources :views, path: :v, only: [:show]

  root "links#index"
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user, optional: true
  has_many :views, dependent: :destroy

  scope :recent_first, -> { order(created_at: :desc) }

  validates :url, presence: true

  after_save_commit if: :url_previously_changed? do
    MetadataJob.perform_later(to_param)
  end

  def self.find(id)
    super Base62.decode(id)
  end

  def to_param
    Base62.encode(id)
  end

  def domain
    URI(url).host rescue StandardError URI::InvalidURIError
  end

  def editable_by?(user)
    user_id? && (user_id == user&.id)
  end
end

app/controllers/admin/links_controller.rb
module Admin
  class LinksController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :check_if_editable, only: [:edit, :update, :destroy]

  def index
    @pagy, @links = pagy(Link.recent_first)
    @link ||= Link.new
  rescue Pagy::OverflowError
    redirect_to root_path
  end

  def show
  end

  def create
    @link = Link.new(link_params.with_defaults(user: current_user))

    if @link.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.turbo_stream do
          render turbo_stream: turbo_stream.prepend('links', @link)
        end
      end
    else
      index
      render :index, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @link.update(link_params)
      redirect_to @link
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @link.destroy
    redirect_to root_path, notice: "Link has been Deleted"
  end

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to root_path, alert: 'Missing Link!'
  end

  private

  def link_params
    params.require(:link).permit(:url)
  end

  def check_if_editable
    return if @link.editable_by?(current_user)

    redirect_to @link, alert: "You don't have permission to edit this!"
  end
end

app/views/links/_form.html.erb
<%= form_with model: link, data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" } do |form| %>
  <div class="form-group flex gap-2 items-center">
    <%#= form.label :title, class: "form-label" %>
    <%= form.url_field :url, required: true, autofocus: true, placeholder: "https://example.org", class: "form-control flex-grow rounded" %>
    <%= form.button "Save", class: "btn btn-success h-full" %>
  </div>
<% end %>

app/views/links/_link.html.erb
<div id="<%= dom_id(link) %>">
  <%= turbo_stream_from link %>

  <div class="grid grid-cols-8 items-center py-4">
    <div class="col-span-5">
      <%= link_to view_path(link), target: :_blank, data: {turbo: false}, class: "no-underline" do %>
        <%= favicon_image_tag link.domain, class: "inline-block m-0" %>
        <%= link.title || link.url %>
        <%= tag.div link.description, class: "text-xs text-gray-700" %>
        <i class="fa-solid fa-arrow-up-right-from-square inline-block w-4 h-4"></i>
      <% end %>
    </div>

    <div class="col-span-2 text-center text-xs">
      <%= link_to(
        pluralize(link.views_count, "view"),
        link,
        class: "px-2 py-1.5 rounded bg-gray-100 no-underline"
      )%>
    </div>

    <div class="text-center text-xs">
      <%= button_tag(
        "Copy",
        class: "btn btn-primary",
        data: { controller: "clipboard", clipboard_text: view_url(link) }
      )%>
    </div>
  </div>
</div>

app/views/links/edit.html.erb
<h1>Edit Link</h1>

<%= render partial: "form", locals: { link: @link } %>

<div class="flex my-3 gap-3 items-center">
  <%= link_to "Cancel", @link, class: "btn btn-light" %>
  <span>or</span>
  <%= button_to "Delete", @link, method: :delete, data: { turbo_confirm: "Are you Sure?" }, class: "btn btn-danger" %>
</div>

app/views/links/index.html.erb
<%= render partial: "form", locals: { link: @link } %>

<div id="links" class="flex flex-col divide-y divide-gray-100 mb-5">
  <%= render @links %>
</div>

<% if @pagy.pages > 1 %>
  <div class="flex justify-center mb-5">
    <%== pagy_nav(@pagy) %>
  </div>
<% end %>

app/views/links/show.html.erb
<div class="flex justify-between items-center text-xs">
  <%= link_to "← Back to all links", root_path, class: "no-underline text-xs px-3 py-2 rounded bg-gray-100" %>
  <div class="flex items-center gap-4">
    <%= tag.div pluralize(@link.views_count, "view") %>
    <%= button_tag "Copy", class: "font-medium px-2 py-1.5 rounded bg-gray-100 no-underline", data: {controller: "clipboard", clipboard_text: view_url(@link)} %>
    <%= link_to "Edit", edit_link_path(@link), class: "px-2 py-1.5 rounded bg-gray-100 no-underline" if @link.editable_by?(current_user) %>
  </div>
</div>

<h1 class="mt-4"><%= @link.url %></h1>
<%= tag.div @link.description %>

<%= link_to view_path(@link), target: :_blank, data: {turbo: false}, class: "text-xs px-2 py-1.5 rounded bg-gray-100 no-underline" do %>
  <%= favicon_image_tag @link.domain, class: "inline-block" %>
  <%= truncate @link.url %>
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="inline-block w-4 h-4">
    <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
  </svg>
<% end %>
<%= line_chart @link.views.group_by_day(:created_at, range: 2.weeks.ago..Time.now, expand_range: true).count %>